[tools]
flux2 = "latest"
gh = "latest"
k3d = "latest"
k9s = "latest"
kubectl = "latest"
pre-commit = "latest"
python = "3.13"
ruff = "latest"
trivy = "latest"
uv = "latest"

[settings]
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["python"]
experimental = true

[env]
APP_REPO = 'study'
GITOPS_REPO = 'study-app-gitops'

[hooks]
enter = "bash ./scripts/setup_project"

[tasks.k8s-setup-local]
description = "Set up a Kubernetes cluster that builds the local images and applies them"
run = "bash ./kubernetes/setup_cluster_local"

[tasks.k8s-setup-minimal]
description = "Set up a minimal Kubernetes cluster"
run = "bash ./kubernetes/setup_cluster_minimal"

[tasks.setup-keys]
description = "Setup deploy keys for the gitops repo"
run = "bash ./scripts/setup_deploy_key"

[tasks.k8s-setup-gitops]
description = "Setup a cluster configured with GitOps using Flux"
run = "bash ./kubernetes/setup_cluster_gitops"
